### ISSUE TITLE
Grafana 7.0 compatibility

### ISSUE THREAD

**Issue by carlosgumz** [gipong/grafana-groupedbarchart-panel#29]
Hello,

Is this plugin already compatible with Grafana 7.0?

I am encountering some problems in this version.

**Comment by truj** [comment]
We just upgraded from Grafana 6.4.4 to 7.1.0.
I can confirm that the graph rendering of this plugin doesn't work any more. Other graph types still work.

JS-Error:
```
angular.js:14800 TypeError: Cannot read property 'Dark' of undefined
    at getCurrentThemeName (ctrl.js:38)
    at getCurrentTheme (ctrl.js:39)
    at new groupedBarChart (ctrl.js:124)
    at onRender (ctrl.js:444)
    at s.eval (ctrl.js:467)
    at s.emit (index.js:202)
    at e.value (emitter.ts:29)
    at GroupedBarChartCtrl.value (panel_ctrl.ts:102)
    at panel_directive.ts:64
    at angular.js:20566
```
The Query produced by grafana still works, and **Inspect > Data** shows correct data.
But the rendering of the panel is broken.

Maybe this is related to #12?

**Comment by truj** [comment]
@carlosgumz Why did you close this issue?
Did you make it work somehow?
If yes, how?
