### ISSUE TITLE
Errors when we switch between bar chart and stacked bar chart

### ISSUE THREAD

**Issue by hanumesh** [gipong/grafana-groupedbarchart-panel#38]
Uncaught TypeError: Cannot read property 'style' of undefined
    at SVGGElement.eval (ctrl.js:362)
    at SVGGElement.eval [as __onmouseover] (d3.v3.min.js:1)

**Comment by gipong** [comment]
I can't reproduce this issue in grafana v7.0. Could you please update to the latest version of this plugin?

**Comment by hanumesh** [comment]
Working with latest plugin version
